name: "Copy Azure MySQL Config Files"
description: "Copy in configuration files required when running with an Azure MySQL server"
inputs:
  SYMFONY_ROOT:
    required: true
    description: "The path (relative to the project's root) in which the Symfony files are stored (e.g. config, src, etc)"

runs:
  using: "composite"
  steps:
    - name: Copy in config files
      shell: bash
      run: |
        cp ./reusable-workflow/.azure/config/database.yaml ${{ inputs.SYMFONY_ROOT }}/config/database.yaml
        mkdir -p ${{ inputs.SYMFONY_ROOT }}/config/db
        cp ./reusable-workflow/.azure/config/db/DigiCertGlobalRootCA.crt.pem ${{ inputs.SYMFONY_ROOT }}/config/db/DigiCertGlobalRootCA.crt.pem