name: "Copy Azure Flysystem Config Files"
description: "Copy in configuration files required when using Flysystem with Azure"
inputs:
  SYMFONY_ROOT:
    required: true
    description: "The path (relative to the project's root) in which the Symfony files are stored (e.g. config, src, etc)"

runs:
  using: "composite"
  steps:
    - name: Copy in config files
      shell: bash
      run: cp ./reusable-workflow/.azure/config/packages/flysystem.yaml ${{ inputs.SYMFONY_ROOT }}/config/packages/flysystem.yaml